const songs = [
  {
    id: 0,
    sname: "Lut Gaye",
    simage: "https://wallpaperaccess.com/full/5604691.jpg",
    artist: "Jubin Nautiyal",
    plays: 10,
    albumName: "Lut Gaye",
    duration: "4:30",
  },
  {
    id: 1,
    sname: "Lut Gaye",
    simage: "https://wallpaperaccess.com/full/5604691.jpg",
    artist: "Jubin Nautiyal",
    plays: 10,
    albumName: "Lut Gaye",
    duration: "4:30",
  },
  {
    id: 2,
    sname: "Lut Gaye",
    simage: "https://wallpaperaccess.com/full/5604691.jpg",
    artist: "Jubin Nautiyal",
    plays: 10,
    albumName: "Lut Gaye",
    duration: "4:30",
  },
  {
    id: 3,
    sname: "Lut Gaye",
    simage: "https://wallpaperaccess.com/full/5604691.jpg",
    artist: "Jubin Nautiyal",
    plays: 10,
    albumName: "Lut Gaye",
    duration: "4:30",
  },
  {
    id: 4,
    sname: "Lut Gaye",
    simage: "https://wallpaperaccess.com/full/5604691.jpg",
    artist: "Jubin Nautiyal",
    plays: 10,
    albumName: "Lut Gaye",
    duration: "4:30",
  },
  {
    id: 5,
    sname: "Lut Gaye",
    simage: "https://wallpaperaccess.com/full/5604691.jpg",
    artist: "Jubin Nautiyal",
    plays: 10,
    albumName: "Lut Gaye",
    duration: "4:30",
  },
  {
    id: 6,
    sname: "Lut Gaye",
    simage: "https://wallpaperaccess.com/full/5604691.jpg",
    artist: "Jubin Nautiyal",
    plays: 10,
    albumName: "Lut Gaye",
    duration: "4:30",
  },
  {
    id: 7,
    sname: "Lut Gaye",
    simage: "https://wallpaperaccess.com/full/5604691.jpg",
    artist: "Jubin Nautiyal",
    plays: 10,
    albumName: "Lut Gaye",
    duration: "4:30",
  },
];

export default songs;
